
var_1: &cache_key mosaic-cache-{{ checksum "package.json" }}

anchor_job_defaults: &job_defaults
  working_directory: ~/mosaic
  docker:
    - image: ptsecurity/node-container:0.0.4

version: 2
jobs:

  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run: npm install
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
      - run: npm run mosaic:build

   deploy:
     <<: *job_defaults
     steps:
       - checkout
       - restore_cache:
           key: *cache_key
       - run: npm install
       - run: npm run mosaic:build



workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
             branches:
               only: master

